"""
R DIDmultiplegtDYN parity tests for the dCDH estimator.

Loads pre-computed golden values from
``benchmarks/data/dcdh_dynr_golden_values.json`` (generated by the R
script at ``benchmarks/R/generate_dcdh_dynr_test_values.R``) and asserts
that the Python ``ChaisemartinDHaultfoeuille`` implementation matches R
``did_multiplegt_dyn`` at l = 1 (which is numerically identical to the
AER 2020 paper's ``DID_M``).

**R is only needed to regenerate the JSON file**, not to run these tests.
The committed JSON is loaded directly and the assertions run on any
Python-only environment. Tests skip ONLY if the JSON file is absent
(run the R script to populate it). The ``require_r_dcdh`` fixture is
intentionally NOT used here so the parity regression suite remains
active in CI even when DIDmultiplegtDYN is unavailable.

Tolerances follow the existing ``test_csdid_ported.py`` convention:
``rtol=1e-4`` for pure-direction point estimates, looser tolerances for
SEs and mixed-direction scenarios (see class docstring).
"""

import json
from pathlib import Path

import pandas as pd
import pytest

from diff_diff import ChaisemartinDHaultfoeuille

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

GOLDEN_VALUES_PATH = (
    Path(__file__).parents[1] / "benchmarks" / "data" / "dcdh_dynr_golden_values.json"
)


@pytest.fixture(scope="module")
def golden_values():
    """
    Load R DIDmultiplegtDYN golden values from the committed JSON file.

    Skips ONLY if the JSON file is absent (R is not needed to run this
    fixture — the committed JSON is the source of truth). To regenerate
    the JSON, run::

        Rscript benchmarks/R/generate_dcdh_dynr_test_values.R

    which requires R + the `DIDmultiplegtDYN` and `jsonlite` packages.
    """
    if not GOLDEN_VALUES_PATH.exists():
        pytest.skip(
            f"dCDH golden values file not found at {GOLDEN_VALUES_PATH}; "
            "run: Rscript benchmarks/R/generate_dcdh_dynr_test_values.R"
        )
    with open(GOLDEN_VALUES_PATH) as f:
        return json.load(f)["scenarios"]


def _golden_to_df(data_dict: dict) -> pd.DataFrame:
    """Reconstruct a panel DataFrame from a golden-values data export."""
    return pd.DataFrame(
        {
            "group": data_dict["group"],
            "period": data_dict["period"],
            "treatment": data_dict["treatment"],
            "outcome": data_dict["outcome"],
        }
    )


def _fit_dcdh_l1(df: pd.DataFrame):
    """Fit ChaisemartinDHaultfoeuille at l=1 and return the results object."""
    est = ChaisemartinDHaultfoeuille()
    return est.fit(
        df,
        outcome="outcome",
        group="group",
        time="period",
        treatment="treatment",
    )


# ---------------------------------------------------------------------------
# Parity tests — one per scenario in the golden values JSON
# ---------------------------------------------------------------------------


class TestDCDHDynRParity:
    """
    Each scenario asserts |python - r| within tolerance for DID_1.

    Tolerances by scenario type:

    - **Pure-direction scenarios** (``joiners_only``, ``leavers_only``):
      tight ``POINT_RTOL = 1e-4`` (0.01%). Python and R agree exactly when
      every switching cohort uses controls of a single baseline type.
    - **Hand-calculable worked example**: exact arithmetic agreement
      (``abs=1e-6``).
    - **Mixed-direction scenarios** (``single_switch_mixed``,
      ``mixed_single_switch``): looser ``MIXED_POINT_RTOL = 0.025`` (2.5%).
      Python implements the AER 2020 Theorem 3 formula with period-based
      stable-control sets (``stable_0(t)`` is any cell with
      ``D_{,t-1}=D_{,t}=0``); R ``DIDmultiplegtDYN`` implements the
      dynamic-companion-paper formula with cohort-based control sets
      (additionally requires ``D_{g,1}`` to match the side). The two
      formulas agree exactly when no group's baseline is on the opposite
      side of where it currently sits — i.e., always for pure-direction
      panels and for the worked example. They disagree by O(1%) when both
      joiners and leavers exist AND some joiners' post-switch cells could
      serve as leavers' controls (or vice versa). This is documented in
      ``REGISTRY.md`` under ``ChaisemartinDHaultfoeuille`` as a
      ``**Note (deviation from R DIDmultiplegtDYN):**``.
    """

    POINT_RTOL = 1e-4
    MIXED_POINT_RTOL = 0.025  # See class docstring for justification.
    SE_RTOL = 1e-3
    MIXED_SE_RTOL = 0.10  # SE is also affected by the cohort/period control set choice.

    def test_parity_single_switch_mixed(self, golden_values):
        scenario = golden_values.get("single_switch_mixed")
        if scenario is None:
            pytest.skip("scenario 'single_switch_mixed' not in golden values")
        df = _golden_to_df(scenario["data"])
        results = _fit_dcdh_l1(df)
        r_results = scenario["results"]
        # Mixed scenario: see class docstring re. cohort vs. period control sets.
        # Point estimate is checked at 2.5% rtol; SE comparison is intentionally
        # omitted because the SE depends on the same cohort-vs-period design
        # choice and is fundamentally apples-to-oranges between the two
        # implementations on mixed-direction panels.
        assert results.overall_att == pytest.approx(
            r_results["overall_att"], rel=self.MIXED_POINT_RTOL
        )

    PURE_DIRECTION_SE_RTOL = 0.05  # 5% rtol on pure-direction scenarios after the full IF fix

    def test_parity_joiners_only(self, golden_values):
        scenario = golden_values.get("joiners_only")
        if scenario is None:
            pytest.skip("scenario 'joiners_only' not in golden values")
        df = _golden_to_df(scenario["data"])
        results = _fit_dcdh_l1(df)
        r_results = scenario["results"]
        # Pure-direction scenario: tight point-estimate parity expected
        # (cell counts and the full IF formula produce identical answers
        # to R DIDmultiplegtDYN under pure-direction conditions).
        assert results.overall_att == pytest.approx(r_results["overall_att"], rel=self.POINT_RTOL)
        # SE parity: looser 5% rtol because Python's cohort-recentered
        # plug-in formula and R's may use slightly different small-sample
        # corrections. The full Lambda^G_{g,l=1} influence function fix
        # narrowed this gap from ~18% to ~3% on the test scenarios.
        assert results.overall_se == pytest.approx(
            r_results["overall_se"], rel=self.PURE_DIRECTION_SE_RTOL
        )

    def test_parity_leavers_only(self, golden_values):
        scenario = golden_values.get("leavers_only")
        if scenario is None:
            pytest.skip("scenario 'leavers_only' not in golden values")
        df = _golden_to_df(scenario["data"])
        results = _fit_dcdh_l1(df)
        r_results = scenario["results"]
        # Pure-direction scenario: tight point-estimate + 5% SE parity
        assert results.overall_att == pytest.approx(r_results["overall_att"], rel=self.POINT_RTOL)
        assert results.overall_se == pytest.approx(
            r_results["overall_se"], rel=self.PURE_DIRECTION_SE_RTOL
        )

    def test_parity_mixed_single_switch(self, golden_values):
        scenario = golden_values.get("mixed_single_switch")
        if scenario is None:
            pytest.skip("scenario 'mixed_single_switch' not in golden values")
        df = _golden_to_df(scenario["data"])
        results = _fit_dcdh_l1(df)
        r_results = scenario["results"]
        # Mixed scenario: see class docstring re. cohort vs. period control sets.
        assert results.overall_att == pytest.approx(
            r_results["overall_att"], rel=self.MIXED_POINT_RTOL
        )

    def test_parity_hand_calculable_worked_example(self, golden_values):
        """
        Cross-check the 4-group worked example panel against R.

        This is the panel where the Python implementation produces
        DID_M = 2.5 exactly. R DIDmultiplegtDYN should agree (modulo
        small numerical differences in how SE is computed).
        """
        scenario = golden_values.get("hand_calculable_worked_example")
        if scenario is None:
            pytest.skip("scenario 'hand_calculable_worked_example' not in golden values")
        df = _golden_to_df(scenario["data"])
        results = _fit_dcdh_l1(df)
        r_results = scenario["results"]
        # Tight tolerance for this exact-arithmetic case
        assert results.overall_att == pytest.approx(r_results["overall_att"], abs=1e-6)


# ---------------------------------------------------------------------------
# Phase 2: Multi-horizon parity tests
# ---------------------------------------------------------------------------


def _fit_dcdh_multi(df: pd.DataFrame, L_max: int):
    """Fit ChaisemartinDHaultfoeuille with L_max and return results."""
    est = ChaisemartinDHaultfoeuille()
    return est.fit(
        df,
        outcome="outcome",
        group="group",
        time="period",
        treatment="treatment",
        L_max=L_max,
    )


class TestDCDHDynRParityMultiHorizon:
    """
    Multi-horizon parity tests against R DIDmultiplegtDYN ``effects > 1``.

    Each scenario asserts per-horizon |python - r| within tolerance for
    DID_l at each horizon l = 1..L_max. The multi-horizon scenarios
    are generated by the R script with ``effects = 3`` or ``effects = 5``
    and ``placebo > 0``.

    Tolerances follow the same convention as the l=1 parity tests:
    pure-direction at 1e-4 for point estimates, looser for SEs and
    mixed-direction panels.
    """

    POINT_RTOL = 1e-4
    MIXED_POINT_RTOL = 0.025
    SE_RTOL = 0.05

    def _check_multi_horizon(self, golden_values, scenario_name, L_max, rtol):
        scenario = golden_values.get(scenario_name)
        if scenario is None:
            pytest.skip(f"scenario '{scenario_name}' not in golden values")
        r_effects = scenario["results"].get("effects", {})
        if not r_effects:
            pytest.skip(f"scenario '{scenario_name}' has no multi-horizon effects")
        df = _golden_to_df(scenario["data"])
        results = _fit_dcdh_multi(df, L_max=L_max)

        for horizon_str, r_data in r_effects.items():
            horizon = int(horizon_str)
            if horizon not in results.event_study_effects:
                continue
            py_eff = results.event_study_effects[horizon]["effect"]
            r_eff = r_data["overall_att"]
            assert py_eff == pytest.approx(r_eff, rel=rtol), (
                f"Horizon {horizon}: Python DID_{horizon}={py_eff:.6f} vs "
                f"R DID_{horizon}={r_eff:.6f} (rtol={rtol})"
            )

    def test_parity_joiners_only_multi_horizon(self, golden_values):
        self._check_multi_horizon(
            golden_values, "joiners_only_multi_horizon", L_max=3, rtol=self.POINT_RTOL
        )

    def test_parity_leavers_only_multi_horizon(self, golden_values):
        self._check_multi_horizon(
            golden_values, "leavers_only_multi_horizon", L_max=3, rtol=self.POINT_RTOL
        )

    def test_parity_mixed_single_switch_multi_horizon(self, golden_values):
        self._check_multi_horizon(
            golden_values, "mixed_single_switch_multi_horizon",
            L_max=5, rtol=self.MIXED_POINT_RTOL,
        )

    def test_parity_joiners_only_long_multi_horizon(self, golden_values):
        self._check_multi_horizon(
            golden_values, "joiners_only_long_multi_horizon",
            L_max=5, rtol=self.POINT_RTOL,
        )
